[profile.default]
evm_version = "paris"
solc-version = "0.8.24"
optimizer = true
optimizer-runs = 200
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts-ccip/=lib/ccip/contracts/",
    "@chainlink/contracts/=lib/chainlink/contracts/",
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
